### ISSUE TITLE
JS/CSS Cache Breaking On Site Restart

### ISSUE THREAD

**Issue by steveshogren** [steveshogren/overseer#19]

**Comment by thedreadpirate** [comment]
Does this need to happen on restart or redeploy?

**Comment by steveshogren** [comment]
Just whenever the JS changes, so redeploy. Is there a good option for this that you know of already? Rename the static content each time?

**Comment by thedreadpirate** [comment]
How do you deploy the site? You're source controlling the browserified file, right?

**Comment by steveshogren** [comment]
Yes, right now I'm checking in that app.js file and jar. I deploy it via the typical heroku "git push".
