### ISSUE TITLE
Write user documentation

### ISSUE THREAD

**Issue by schmave** [steveshogren/overseer#43]
It would be nice to share a brief description of what Custodia can do, and how to use it both as a student and as an administrator. Maybe this already exists?

**Comment by steveshogren** [comment]
It does not, I can put something like that together.

**Comment by steveshogren** [comment]
I figure this is good enough:

https://github.com/steveshogren/overseer/wiki/Custodia-Usage

**Comment by schmave** [comment]
Cool, looks good!
