### ISSUE TITLE
Add option for highlighting late swipes on the main student dashboard

### ISSUE THREAD

**Issue by schmave** [steveshogren/overseer#53]
e.g. PFS hopes to see all people who signed in after 10:15am highlighted in red.

**Comment by steveshogren** [comment]
Hm, so this feature sort of conflicts with the short time. If it's late, it might not be short, right? And vice versa. I suppose I'll put it in any way, but it feels like a feature that could be easily confused with the short time.

**Comment by steveshogren** [comment]
I can always remove or rework them both into some other feature that better captures the intent, but for now I can't think of a better way to do it.

**Comment by steveshogren** [comment]
For now, this is just at the sql level only, defaulting to 10:15.
