### ISSUE TITLE
Color for excused absence is ambiguous

### ISSUE THREAD

**Issue by schmave** [steveshogren/overseer#56]
The color shown for excused absences on the student calendar report is the same as is shown for 0-285 minutes of attendance, so you can't tell which is which at a glance.

**Comment by steveshogren** [comment]
I think this might be because you currently have to refresh the page to see the new color. I'll fix that.

**Comment by steveshogren** [comment]
But I could see how they'd want to tell them apart, I'll look into that.

**Comment by schmave** [comment]
I'm testing with version a47b158b321228cf2bdef533f1c87769b9b6e75b and excused absences show up in the dark green color.

**Comment by steveshogren** [comment]
This should work now by showing up orange.
